permalink: /posts/:title
markdown: kramdown
  
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

name: Ph.D. Student
url: diggi0330.github.io
enforce_ssl: diggi0330.github.io
description: Digvijay's personal website

collections:
  ml:
    output: true
  math:
    output: true

defaults:
  - scope:
      path: ""
      type: ml
    values:
      layout: post
  - scope:
      path: ""
      type: math
    values:
      layout: post
